import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { GoogleTagManager } from "@/lib/gtm";
import CookieBanner from "@/components/cookies";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId={process.env.NEXT_PUBLIC_GTM_ID!} />

      <body className={inter.className}>
        {children}
        <CookieBanner />
      </body>
    </html>
  );
}
